services:
  auth-db:
    image: mongo:6.0
    container_name: project_template_auth_db
    hostname: auth-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${AUTH_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${AUTH_MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${AUTH_MONGO_DBNAME}
      TZ: Europe/Sofia
    ports:
      - "5450:27017"
    volumes:
      - auth-db-data:/data/db
    networks:
      - project_template_network   
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: project_template_backend
    depends_on:
      - auth-db
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    networks:
      - project_template_network

volumes:
  auth-db-data:
    driver: local
    name: auth-db-data

networks:
  project_template_network:
    driver: bridge
    name: project_template_network
